qup/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('polls/', include('polls.urls')),
    path('rooms/', include('room.urls')),
    path('admin/', admin.site.urls),
]

room/urls.py
from django.urls import path

from . import views

app_name = 'room'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('new/', views.create_room, name='new'),
    # path('<int:question_id>/vote/', views.vote, name='vote'),
]

room/models.py
from django.db import models


class Room(models.Model):
  code = models.CharField(max_length=4)
  group_name = models.CharField(max_length=100)
  created_date = models.DateTimeField('date created')

  def __str__(self):
    return f"Room code: {self.code}"

room/forms.py
from django import forms

class RoomForm(forms.Form):
    room_name = forms.CharField(label='Your group name', max_length=100)

room/views.py
from django.shortcuts import render
from datetime import datetime

from django.http import HttpResponse, HttpResponseRedirect
from django.http import Http404
from django.template import loader
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic
from .models import Room
from .forms import RoomForm
from .helpers import id_generator

class IndexView(generic.ListView):
  template_name = 'rooms/index.html'
  context_object_name = 'current_room_list'

  def get_queryset(self):
    """Return the last five created rooms."""
    return Room.objects.order_by("-created_date")[:5]

class DetailView(generic.DetailView):
  model = Room
  template_name = "rooms/detail.html"

def create_room(request):
    # if this is a POST request we need to process the form data
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = RoomForm(request.POST)
        # check whether it's valid:
        if form.is_valid():
            room_name = form.cleaned_data.get('room_name')
            code = id_generator()

            room = Room(code=code, group_name=room_name, created_date=datetime.now())

            room.save()
            # process the data in form.cleaned_data as required
            # ...
            # redirect to a new URL:
            return HttpResponseRedirect('/rooms/')

    # if a GET (or any other method) we'll create a blank form
    else:
        form = RoomForm()

    return render(request, 'rooms/new.html', {'form': form})

room/templates/rooms/detail.html
<!DOCTYPE html>
<html>
  <body>
    <!-- 1. The <iframe> (and video player) will replace this <div> tag. -->
    <div id="player"></div>

    <script>
      // 2. This code loads the IFrame Player API code asynchronously.
      var tag = document.createElement('script');

      tag.src = "https://www.youtube.com/iframe_api";
      var firstScriptTag = document.getElementsByTagName('script')[0];
      firstScriptTag.parentNode.insertBefore(tag, firstScriptTag);

      // 3. This function creates an <iframe> (and YouTube player)
      //    after the API code downloads.
      var player;
      function onYouTubeIframeAPIReady() {
        player = new YT.Player('player', {
          height: '390',
          width: '640',
          videoId: 'M7lc1UVf-VE',
          events: {
            'onReady': onPlayerReady,
            'onStateChange': onPlayerStateChange
          }
        });
      }

      // 4. The API will call this function when the video player is ready.
      function onPlayerReady(event) {
        event.target.playVideo();
      }

      // 5. The API calls this function when the player's state changes.
      //    The function indicates that when playing a video (state=1),
      //    the player should play for six seconds and then stop.
      var done = false;
      function onPlayerStateChange(event) {
        if (event.data == YT.PlayerState.PLAYING && !done) {
          setTimeout(stopVideo, 6000);
          done = true;
        }
      }
      function stopVideo() {
        player.stopVideo();
      }
    </script>
  </body>
</html>

room/templates/rooms/index.html
{% if current_room_list %}
    <ul>
    {% for room in current_room_list %}
      <li><a href="{% url 'room:detail' room.id %}">{{ room.group_name }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No rooms are available.</p>
{% endif %}

room/templates/rooms/new.html
<h1> NEw </h1>
<form action="/rooms/new/" method="post">
  {% csrf_token %}
  {{ form }}
  <input type="submit" value="Submit">
</form>